Update kentico.gitignore
Kentico/KenticoGitignore pull request #3
Opened 2017-02-09 14:14 UTC by cjfphilip

I noticed that when installing Kentico 10 the DeviceProfiles folder is plural and not singular "DeviceProfile". Unless this ignore file is for a different version of Kentico.

2017-02-09 16:25 UTC, ChristopherJennings requested changes
Hi Charles, 

Thanks for the pull request. This ignore was originally designed for Kentico version 9. Rather than breaking the ignore for 9, can you modify this to simply add another line ignoring the plural version for version 10? Have you found anything else that needs to be re-ignored, added or removed?

2017-02-09 16:25 UTC, ChristopherJennings commented on kentico.gitignore
> +CMS/App_Data/CMSModules/DeviceProfiles/logFiftyOne.txt
Can you modify this to simply add another line ignoring the plural version for version 10?

2017-02-10 15:16 UTC, cjfphilip commented
I have added this to my local file:
```
**/[Bb]in/**/*
!**/[Bb]in/**/
!*.refresh
```
so that .refresh files will be included to restore missing dll's. but I'm not sure if this is good or not, so I haven't submitted it in here.

2017-02-10 19:14 UTC, ChristopherJennings approved these changes

2017-02-10 19:15 UTC, merged

2017-02-10 19:21 UTC, ChristopherJennings commented
Thanks for the update! regarding the secondary changes you mentioned, those are file-based references specific to web site projects (rather than web application projects). My understanding is that they should be included in source control as they point to where the project can get the DLL if needed. It wouldn't be a bad idea to include this in the ignore, but commented out with an explanation as to why you would uncomment it. If you'd like to contribute this, please open another pull request, and I'll happily bring that in.